name: Deploy to production
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Deploy to production
        run: |
          cd /home/smaug/discord_bots/sheweny-bot/
          git stash
          git pull origin main
          yarn
          yarn build
          pm2 BOT_TOKEN="{{secrets.BOT_TOKEN}}" reload ecosystem.config.js
